name: Check Openshift

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  openshift:
    name: Openshift 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        openshift: [v3.11.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-


      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.3
        with:
          oc version: ${{ matrix.openshift }}
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Openshift usage
        run: |
          echo "Current path:"
          pwd
          echo "All files:"
          ls -al
          echo "Logging in...."
          oc login -u admin -p admin
          echo "New project"
          oc new-project tests
          echo "Registry login"
          oc registry login --skip-check
          echo "Registry info"
          OPENSHIFT_IMAGE_REGISTRY=$(oc registry info)
          echo "info was: $OPENSHIFT_IMAGE_REGISTRY"
          echo "login to docker registry"
                    
          
          # Try the admin user instead
          #docker login -u openshift -p $(oc whoami -t)  $OPENSHIFT_IMAGE_REGISTRY
          echo "oc whoami"
          oc whoami
          echo "oc whoami -t"
          oc whoami -t
          docker login -u admin -p $(oc whoami -t)  $OPENSHIFT_IMAGE_REGISTRY
          
          echo "login done!"
          echo "Pull, tag and push image to registry"
          # pull and push an image
          echo "Pull"
          docker pull alpine:3.14
          echo "Tag"
          docker tag alpine:3.14 $OPENSHIFT_IMAGE_REGISTRY/tests/alpine:3.14
          echo "Push"
          docker push $OPENSHIFT_IMAGE_REGISTRY/tests/alpine:3.14
          echo "Pushed!"
          
          
          echo "All files:"
          ls -al

          # echo "All files recursive:"
          # ls -alR

          echo "Try to change permissions recursively"
          # sudo chmod -R 755 .
          sudo bash -c 'sudo chmod -R 777 .'
          
