name: Check Openshift

on:
  push:
  workflow_dispatch:

env:
  # Env vars for authentication for the tests using OpenShift
  OPENSHIFT_USER: admin
  OPENSHIFT_PWD: admin
  OPENSHIFT_NS: testing

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [v3.11.0, v4.1.0, 4.10.0, v4.10.0]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup OpenShift
        if: inputs.type == 'Openshift'
        uses: manusa/actions-setup-openshift@v1.1.3
        with:
          oc version: ${{ matrix.version }}
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Openshift usage
        if: inputs.type == 'Openshift'
        run: |
          
          # Not sure if this is the right fix but there are a few instances where the connection
          # to the registry is refused.
          
          echo "Logging in..."
          oc login -u $OPENSHIFT_USER -p $OPENSHIFT_PWD
          echo "New project: $OPENSHIFT_NS"
          oc new-project $OPENSHIFT_NS
          echo "Registry login"
          oc registry login --skip-check
          echo "Registry info"
          OPENSHIFT_IMAGE_REGISTRY=$(oc registry info)
          echo "OPENSHIFT_IMAGE_REGISTRY=${OPENSHIFT_IMAGE_REGISTRY}" >> $GITHUB_ENV
          echo "Registry url: $OPENSHIFT_IMAGE_REGISTRY"
          
          # echo "login to docker registry"        
          # docker login -u $(oc whoami) -p $(oc whoami -t)  $OPENSHIFT_IMAGE_REGISTRY
          
          # Set extra Maven parameters for OpenShift
          TMP=" -Popenshift-tests -Ddekorate.docker.registry=$OPENSHIFT_IMAGE_REGISTRY -Ddekorate.docker.group=$OPENSHIFT_NS"
          echo "OPENSHIFT_MAVEN_PARAMETERS=${TMP}" >> $GITHUB_ENV

      # Sometimes the login to the registry fails with a connection refused
      # See if a retry helps
      - name: Login to OpenShift Image Registry
        if: inputs.type == 'Openshift'
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 2
          retry_wait_seconds: 10
          max_attempts: 3
          command: docker login -u $(oc whoami) -p $(oc whoami -t)  $OPENSHIFT_IMAGE_REGISTRY
