name: Check Openshift

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  openshift:
    name: Openshift 
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        openshift: [v3.11.0]
    steps:
      - name: Set Env Var
        run: |
          TMP=Hola
          echo "$MY_VAR=${TMP}" >> $GITHUB_ENV
      - name: Use Env Var A
        run: echo $TMP
      - name: Use Env Var B
        run: echo ${TMP}
      - name: Use Env Var C
        run: echo ${{TMP}}
      - name: Use Env Var D
        run: echo ${env.TMP}
      - name: Use Env Var D
        run: echo ${{env.TMP}}
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.3
        with:
          oc version: ${{ matrix.openshift }}
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Openshift usage
        run: |
          echo "Logging in..."
          oc login -u admin -p admin
          echo "New project"
          oc new-project tests
          echo "Registry login"
          oc registry login --skip-check
          echo "Registry info"
          OPENSHIFT_IMAGE_REGISTRY=$(oc registry info)
          echo "info was: $OPENSHIFT_IMAGE_REGISTRY"
          echo "login to docker registry"
                    
          
          # Try the admin user instead
          #docker login -u openshift -p $(oc whoami -t)  $OPENSHIFT_IMAGE_REGISTRY
          echo "oc whoami"
          oc whoami
          echo "oc whoami -t"
          oc whoami -t
          docker login -u admin -p $(oc whoami -t)  $OPENSHIFT_IMAGE_REGISTRY
          
          echo "login done!"
          echo "Pull, tag and push image to registry"
          # pull and push an image
          echo "Pull"
          docker pull alpine:3.14
          echo "Tag"
          docker tag alpine:3.14 $OPENSHIFT_IMAGE_REGISTRY/tests/alpine:3.14
          echo "Push"
          docker push $OPENSHIFT_IMAGE_REGISTRY/tests/alpine:3.14
          echo "Pushed!"
          
