name: Run Tests

on:
  workflow_dispatch:
  repository_dispatch:
#     inputs:
#       triggerRepo:
#         description: 'The repository triggering this job'
#         type: string
#         required: true
#       triggerWorkflowRunId:
#         description: "The workflow run id of the job"
#         type: string
#         required: true
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Output
        env:
          #MESSAGE: ${{ github.event.client_payload.message }}
          MESSAGE: ${{ toJSON(github.event) }}
        run: echo $MESSAGE
        
      - name: Determine type
        run: |
          number=$RANDOM
          echo $number
          if [ $((number%2)) -eq 0 ] ; then   
            echo "failing job"
            exit 1
          else
            echo "passing job"
          fi
          
      - name: Report failure
        if: ${{ failure() }}
        run: |
          echo "It failed"

          
      - name: Report success
        if: ${{ success() }}
        run: |
          echo "It passed"
