name: Run Tests
env:
  STATUS_BRANCH: run-status
on:
  workflow_call:
    outputs:
      status:
        description: 0 if job pased, 1 if not
        value: ${{ jobs.run_tests.outputs.status }}
jobs:
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.step2.output-status.status }}
    steps:
      - name: Output
        env:
          #MESSAGE: ${{ github.event.client_payload.message }}
          MESSAGE: ${{ toJSON(github.event.client_payload) }}
        run: echo $MESSAGE

      - name: Checkout run-status branch
        uses: actions/checkout@v3
        with:
          repository: wildfly/wildfly
          path: status      

      - name: Checkout run-status branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.STATUS_BRANCH }}
          path: status      
          
      - name: Determine type
        run: |
          number=$RANDOM
          echo $number
          if [ $((number%2)) -eq 0 ] ; then   
            echo "failing job"
            exit 1
          else
            echo "passing job"
          fi
          
      - name: Report failure
        if: ${{ failure() }}
        run: |
          echo "It failed"
          STATUS="failed"
          echo "STATUS=1" >> $GITHUB_ENV
          
      - name: Report success
        if: ${{ success() }}
        run: |
          echo "It passed"
          STATUS="passed"
          echo "STATUS=0" >> $GITHUB_ENV
          
      - id: output-status
        if: ${{ always() }}
        run: |
          echo "Setting 'status' output to ${STATUS}"
          echo "::set-output name=status::${STATUS}"
